spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
  application:
    name: tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/tracker_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    open-in-view: false